### ISSUE TITLE
Missing location

### ISSUE THREAD

**Issue by jzburda** [flo/m3addon#19]
I keep getting this error when trying to import a HoTS model

Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\__init__.py", line 4553, in execute
    m3import.importM3BasedOnM3ImportOptions(scene)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3import.py", line 1875, in importM3BasedOnM3ImportOptions
    importer.importM3BasedOnM3ImportOptions(scene)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3import.py", line 409, in importM3BasedOnM3ImportOptions
    self.model = m3.loadModel(fileName)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3.py", line 1180, in loadModel
    sections = loadSections(filename, checkExpectedValue)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3.py", line 1123, in loadSections
    section.determineContentField(checkExpectedValue)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3.py", line 45, in determineContentField
    self.content = self.structureDescription.createInstances(buffer=self.rawBytes, count=indexEntry.repetitions, checkExpectedValue=checkExpectedValue)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3.py", line 170, in createInstances
    list.append(self.createInstance(buffer=buffer, offset=instanceOffset, checkExpectedValue=checkExpectedValue));
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3.py", line 150, in createInstance
    return M3Structure(self, buffer, offset, checkExpectedValue)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3.py", line 240, in __init__
    self.readFromBuffer(buffer, offset, checkExpectedValue)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3.py", line 258, in readFromBuffer
    field.readFromBuffer(self, buffer, fieldOffset, checkExpectedValue)
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.74\scripts\addons\m3addon\m3.py", line 648, in readFromBuffer
    raise Exception("Expected that %sV%s.%s has always the value %s, but it was %s" % (owner.structureDescription.structureName, owner.structureDescription.structureVersion, self.name, self.expectedValue, value))
Exception: Expected that PATUV4.unknowne2d91749 has always the value b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', but it was b'\xff\xff\x7f3\x00\x00\x00\x80\x00\x00\x00\x80'

location: <unknown location>:-1

**Comment by flo** [comment]
HotS models aren't supported yet

**Comment by flo** [comment]
Closing old ticket...
